name: Build LaTeX PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: CV_yeonjukim.tex
      - name: Move PDF to docs
        run: mkdir -p docs && mv CV_yeonjukim.pdf docs/resume.pdf
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
